version: "2017-09-20"
pipeline:
- id: build
  type: script
  env:
    NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt
  commands:
  - desc: Build
    cmd: |
      wget -q https://github.com/github/codeql-action/releases/latest/download/codeql-runner-linux
      chmod +x codeql-runner-linux
      ./codeql-runner-linux init --repository "zalando/zappr" --github-url https://github.com --github-auth "dummy_token"
      COMMIT=`git rev-parse HEAD`
      echo "$COMMIT"
      ./codeql-runner-linux analyze --repository "zalando/zappr" --github-url https://github.com --github-auth "dummy_token" --commit "$COMMIT" --ref "refs/heads/master"

      #function npm {
      #  docker run -i --rm -v "$(pwd):/workspace" -w /workspace registry.opensource.zalan.do/stups/node:latest npm "$@"
      #}
      #
      #npm install --no-optional
      #npm run dist
