site_name: Zappr
site_favicon: img/favicon.ico
repo_url: https://github.com/zalando/zappr
docs_dir: docs
pages:
  - Overview: index.md
  - Setup: setup.md
  - Comparison to other tools: competitors.md
  - Run your own: run-your-own.md
  - FAQ: faq.md
  - Terms of Service: tos.md
  - Cookies: cookies.md
  - Imprint and Data protection declaration: imprint.md
extra_css:
  - images.css
